import Head from "next/head";
// 7;
// import RandomSketch from "@/components/audioVisualizer/AudioVisualizer";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";

import TrackPage from "@/components/trackpage/TrackPage";

const inter = Inter({ subsets: ["latin"] });

export default function trackpage() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TrackPage />
        {/* <RandomSketch /> */}
        {/* <MainLayout>
          <Navbar />
          <Hero />
          <ListTrack />
        </MainLayout> */}
      </main>
    </>
  );
}
